### ISSUE TITLE
.interim file not created

### ISSUE THREAD

**Issue by kcygan** [tycheyoung/homs-tc#3]
Hi! I just tried to push a couple of .mgf files through the workflow and I get the following error: 

```
test.pkl does not exist. Running query preprocessing first...
[Query] Classify query by its charge
[Query] Vectorizing: Raw spectra to spectrum vector
[Query] Convert charge: 1 to npz
[Query] Convert charge: 4 to npz
[Query] Convert charge: 2 to npz
[Query] Convert charge: 3 to npz
[Query] Convert charge: 5 to npz
[Query] Convert charge: 6 to npz
[Query] Save query_spectra to pkl
charge,ref_encode_time,query_encode_time,search time,total time
Traceback (most recent call last):
  File "run.py", line 127, in <module>
    main()
  File "run.py", line 117, in main
    output_fname = fdr_postprocessing(std_interim_fname, open_interim_fname,
  File "/home/dnanexus/homs-tc/homs_tc/fdr_postprocessing.py", line 79, in fdr_postprocessing
    df_std = cuda_output_to_df(cuda_std_output)
  File "/home/dnanexus/homs-tc/homs_tc/fdr_postprocessing.py", line 14, in cuda_output_to_df
    df = pd.read_csv(cuda_output_fname, names=header_list, dtype=df_dtypes, delimiter="\t", header=None)
  File "/home/dnanexus/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/dnanexus/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/dnanexus/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/dnanexus/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/dnanexus/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/dnanexus/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/home/dnanexus/.local/lib/python3.8/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'test_std.interim'
```

Any help would be appreciated.

**Comment by tycheyoung** [comment]
Hello,
can you check your output destination folder (for mztab)? 1) is it created beforehand? 2) do you have a write permission there?

**Comment by kcygan** [comment]
I tried both ways. Output in the current working dir and creating one new directory beforehand and outputting there. Both failed. Yes, I have all correct permissions.

**Comment by tycheyoung** [comment]
ah, looks like a CUDA run has been failed? do you have all CUDA-related binary files? If so, what's the log?

**Comment by kcygan** [comment]
I am sorry, I do not fully understand. I do not get any additional log output.

**Comment by kcygan** [comment]
Ok, I investigated a little bit more @tycheyoung. Looks like the problem is that the splib file is not preprocessed correctly i.e. I do not get any *charge*.npz files from splib. I only get them from the query file. Can you see if there is a bug there somewhere? Also, in the run.py file the CNPY_LIB_PATH when added to the LD_LIBRARY_PATH should be unquoted. 
Thanks for you help!

**Comment by tycheyoung** [comment]
Not sure which splib file you are using, but I don't see any bug on my side
Looks like https://github.com/tycheyoung/homs-tc/blob/main/run.py#L73 is not kicked in.
First of all, can you see if `ref_charges` in https://github.com/tycheyoung/homs-tc/blob/main/run.py#L39 is stored properly?

**Comment by kcygan** [comment]
Can you please provide a working "small" example?

**Comment by kcygan** [comment]
> Not sure which splib file you are using, but I don't see any bug on my side Looks like https://github.com/tycheyoung/homs-tc/blob/main/run.py#L73 is not kicked in. First of all, can you see if `ref_charges` in https://github.com/tycheyoung/homs-tc/blob/main/run.py#L39 is stored properly?

Looks like those are not processed correctly...

**Comment by kcygan** [comment]
Ok, it was a problem with the spectral library. Now the ref_charges are processed correctly, however I do encounter another error message: "CUDA code failed. Exiting...". Do you happen to know what is the most likely reason for CUDA code to fail?

**Comment by kcygan** [comment]
Figured that one also. If was the missing architecture. Thanks for your help and the software!
